# Generated by Django 5.2.13 on 2026-05-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('total_issues', models.IntegerField(default=0)),
                ('critical_issues', models.IntegerField(default=0)),
                ('warning_issues', models.IntegerField(default=0)),
                ('suggestion_issues', models.IntegerField(default=0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('raw_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='repositories.pullrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=512)),
                ('line_number', models.IntegerField()),
                ('severity', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('explanation', models.TextField()),
                ('suggested_fix', models.TextField()),
                ('improved_code', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reviews.review')),
            ],
        ),
    ]
