# Generated by Django 5.2.16 on 2026-07-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewissue',
            name='compliance_tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
